-- ---------------------------------------------------------
-- SOLICITAÇÃO DE CRIAÇÃO DE VIEWS PARA EXPORTAÇÃO AO BI
-- ---------------------------------------------------------

/* LISTA:
- ​Visualizar a quantidade e o valor comprado pelos produtos e/ou categorias dos seus produtos;
- ​Visualizar a quantidade e o valor comprado dos seus produtos, geograficamente, pelas cidades;
- ​Visualizar a quantidade e o valor comprado dos seus produtos, por quadrimestre e/ou por ano;
- ​Visualizar a quantidade e o valor comprado dos seus produtos, por estado civil.
- ​Visualizar o ranking dos produtos mais vendidos em um determinado ano;
- ​Visualizar o ranking dos produtos com maior valor de venda por cidade, em um determinado ano;
- ​Visualizar o percentual de venda de cada produto em um determinado quadrimestre e ano;
- ​Visualizar a diferença na quantidade das vendas de cada produto entre dois anos consecutivos;
- ​Visualizar a diferença entre a quantidade e os valores vendidos entre a nossa empresa e a concorrente por quadrimestre e/ou ano.
*/

-- VIEW 1
SELECT 
	P.SK_PRODUTO AS "ID PRODUTO", 
	V.QUANTIDADE_VENDIDA AS "QUANTIDADE VENDIDA", 
	V.VALOR_TOTAL_VENDA AS "VALOR DA VENDA",
	(ROUND((V.VALOR_TOTAL_VENDA / V.QUANTIDADE_VENDIDA), 2)) AS "PREÇO UNITÁRIO",
	P.NOME_PRODUTO AS "NOME DO PRODUTO",
	P.CATEGORIA AS "CATEGORIA DO PRODUTO"
FROM 
	FATO_VENDAS V
INNER JOIN
	DIM_PRODUTO P 
ON 
	(V.SK_PRODUTO = P.SK_PRODUTO);

-- VIEW 2
SELECT
	V.SK_PRODUTO AS "ID PRODUTO",
	V.SK_LOJA AS "ID LOJA",
	P.NOME_PRODUTO AS "NOME DO PRODUTO",
	V.QUANTIDADE_VENDIDA  AS "QUANTIDADE VENDIDA",
	V.VALOR_TOTAL_VENDA  AS "VALOR DA VENDA",
	(ROUND((V.VALOR_TOTAL_VENDA / V.QUANTIDADE_VENDIDA), 2)) AS "PREÇO UNITÁRIO",
	L.NOME_LOJA AS "NOME DA LOJA",
	L.CIDADE AS "CIDADE"
FROM
	FATO_VENDAS V
INNER JOIN
	DIM_LOJA L ON (L.SK_LOJA = V.SK_LOJA)
INNER JOIN
	DIM_PRODUTO P ON (P.SK_PRODUTO  = V.SK_PRODUTO)
;

-- CLAUDE SUGESTOES

CREATE OR REPLACE VIEW VW_FATO_VENDAS_DETALHADA AS
SELECT
    V.SK_TEMPO,
    T.ANO AS ANO,
    T.QUADRIMESTRE AS QUADRIMESTRE,
    P.SK_PRODUTO AS ID_PRODUTO,
    P.NOME_PRODUTO AS NOME_DO_PRODUTO,
    P.CATEGORIA AS CATEGORIA__DO_PRODUTO,
    L.SK_LOJA AS ID_LOJA,
    L.NOME_LOJA AS NOME_DA_LOJA,
    L.CIDADE AS CIDADE,
    EC.ESTADO_CIVIL AS ESTADO_CIVIL,
    V.QUANTIDADE_VENDIDA AS QUANTIDADE_VENDIDA,
    V.VALOR_TOTAL_VENDA AS VALOR_DA_VENDA,
    ROUND((V.VALOR_TOTAL_VENDA / V.QUANTIDADE_VENDIDA), 2) AS PRECO_UNITARIO
FROM FATO_VENDAS V
INNER JOIN DIM_PRODUTO P ON V.SK_PRODUTO = P.SK_PRODUTO
INNER JOIN DIM_LOJA L ON V.SK_LOJA = L.SK_LOJA
INNER JOIN DIM_ESTADO_CIVIL EC ON V.SK_ESTADO_CIVIL = EC.SK_ESTADO_CIVIL
INNER JOIN DIM_TEMPO T ON V.SK_TEMPO = T.SK_TEMPO;

CREATE OR REPLACE VIEW vw_ranking_produtos_ano AS
SELECT
    ANO,
    ID_PRODUTO,
    NOME_DO_PRODUTO,
    SUM(QUANTIDADE_VENDIDA) AS QUANTIDADE_TOTAL,
    RANK() OVER (PARTITION BY ANO ORDER BY SUM(QUANTIDADE_VENDIDA) DESC) AS RANKING
FROM vw_fato_vendas_detalhada
GROUP BY ANO, ID_PRODUTO, NOME_DO_PRODUTO;

CREATE OR REPLACE VIEW vw_ranking_produtos_cidade_ano AS
SELECT
    ANO,
    CIDADE,
    ID_PRODUTO,
    NOME_DO_PRODUTO,
    SUM(VALOR_DA_VENDA) AS VALOR_TOTAL,
    RANK() OVER (PARTITION BY ANO, CIDADE ORDER BY SUM(VALOR_DA_VENDA) DESC) AS RANKING
FROM vw_fato_vendas_detalhada
GROUP BY ANO, CIDADE, ID_PRODUTO, NOME_DO_PRODUTO;

CREATE OR REPLACE VIEW vw_percentual_produto_quadrimestre AS
SELECT
    ANO,
    QUADRIMESTRE,
    ID_PRODUTO,
    NOME_DO_PRODUTO,
    SUM(VALOR_DA_VENDA) AS VALOR_PRODUTO,
    ROUND(
        100.0 * SUM(VALOR_DA_VENDA) / SUM(SUM(VALOR_DA_VENDA)) OVER (PARTITION BY ANO, QUADRIMESTRE),
        2
    ) AS PERCENTUAL
FROM vw_fato_vendas_detalhada
GROUP BY ANO, QUADRIMESTRE, ID_PRODUTO, NOME_DO_PRODUTO;

CREATE OR REPLACE VIEW vw_diferenca_anual_produto AS
SELECT
    ANO,
    ID_PRODUTO,
    NOME_DO_PRODUTO,
    SUM(QUANTIDADE_VENDIDA) AS QUANTIDADE_ANO,
    LAG(SUM(QUANTIDADE_VENDIDA)) OVER (PARTITION BY ID_PRODUTO ORDER BY ANO) AS QUANTIDADE_ANO_ANTERIOR,
    SUM(QUANTIDADE_VENDIDA) - LAG(SUM(QUANTIDADE_VENDIDA)) OVER (PARTITION BY ID_PRODUTO ORDER BY ANO) AS DIFERENCA
FROM vw_fato_vendas_detalhada
GROUP BY ANO, ID_PRODUTO, NOME_DO_PRODUTO;

CREATE OR REPLACE VIEW vw_comparativo_concorrente AS
SELECT
    V.SK_TEMPO,
    T.ANO AS ANO,
    t.QUADRIMESTRE AS QUADRIMESTRE,
    SUM(V.QUANTIDADE_VENDIDA) AS QUANTIDADE_PROPRIA,
    SUM(V.VALOR_TOTAL_VENDA) AS VALOR_PROPRIO,
    FVC.VALOR AS VALOR_CONCORRENTE
FROM FATO_VENDAS V
JOIN FATO_VENDAS_CONCORRENTE FVC ON V.SK_TEMPO = FVC.SK_TEMPO
JOIN DIM_TEMPO T ON V.SK_TEMPO = T.SK_TEMPO
GROUP BY V.SK_TEMPO, FVC.VALOR, T.ANO, T.QUADRIMESTRE;

SELECT * FROM VW_FATO_VENDAS_DETALHADA;
SELECT * FROM VW_RANKING_PRODUTOS_ANO;
SELECT * FROM VW_RANKING_PRODUTOS_CIDADE_ANO;
SELECT * FROM VW_PERCENTUAL_PRODUTO_QUADRIMESTRE;
SELECT * FROM vw_diferenca_anual_produto;
SELECT * FROM VW_COMPARATIVO_CONCORRENTE;
