CREATE TABLE CLIENTES (
    ID_CLIENTE      NUMBER(10),
    NOME            VARCHAR2(150),
    EMAIL           VARCHAR2(150),
    TELEFONE        VARCHAR2(30),
    SEXO            VARCHAR2(20),
    ESTADO_CIVIL    VARCHAR2(30),
    DATA_NASCIMENTO DATE,
    CONSTRAINT PK_STG_CLIENTES PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PRODUTOS (
    ID_PRODUTO      NUMBER(10),
    NOME_PRODUTO    VARCHAR2(150),
    CATEGORIA       VARCHAR2(100),
    PRECO           NUMBER(12,2),
    CONSTRAINT PK_STG_PRODUTOS PRIMARY KEY (ID_PRODUTO)
);

CREATE TABLE PEDIDOS (
    ID_PEDIDO       NUMBER(10),
    ID_CLIENTE      NUMBER(10),
    DATA_PEDIDO     DATE,
    VALOR_TOTAL     NUMBER(12,2),
    CONSTRAINT PK_STG_PEDIDOS PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_STG_PED_CLI FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE ITENS_PEDIDO (
    ID_ITEM         NUMBER(10),
    ID_PEDIDO       NUMBER(10),
    ID_PRODUTO      NUMBER(10),
    NOME_PRODUTO    VARCHAR2(150),
    CATEGORIA       VARCHAR2(100),
    PRECO_UNITARIO  NUMBER(12,2),
    QUANTIDADE      NUMBER(10),
    CONSTRAINT PK_STG_ITENS PRIMARY KEY (ID_ITEM),
    CONSTRAINT FK_STG_ITM_PED FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
    CONSTRAINT FK_STG_ITM_PROD FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);